version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  open-pull-requests-limit: 999
  schedule:
    interval: weekly
  ignore:
  - dependency-name: jest
    versions:
      - ">= 27"
  - dependency-name: ts-jest
    versions:
      - ">= 27"
