version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  ignore:
  - dependency-name: jest
    versions:
      - ">= 27"
  - dependency-name: ts-jest
    versions:
      - ">= 27"
