sudo: false
os:
  - linux
language: node_js
node_js:
  - '12'
cache:
  npm: true
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run test
  - npm run build
branches:
  only:
    - master
