version: '3.8'

services:
  cms_search:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./data:/app/data
    environment:
      - DATAPUNT_API_URL=${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
    env_file: .env.development
