$schema: 'http://json-schema.org/draft-07/schema#'

type: object

properties:
  logging:
    $ref: '#/definitions/logging.dictconfig'
  search_config:
    $ref: '#/definitions/search_config'
  web:
    $ref: '#/definitions/web'
  cors:
    $ref: '#/definitions/cors'

required:
- logging
- search_config
- web


definitions:

  search_config:
    type: object
    properties:
      default_read_timeout:
        type: number
      connect_timeout:
        type: number
      min_query_length:
        type: integer
      max_results:
        type: integer
      results_type:
        type: string
      elastic_host:
        type: string
      elastic_port:
        type: integer
      cms_url:
        type: string
      index:
        type: string
    required:
    - default_read_timeout
    - connect_timeout
    - min_query_length
    - elastic_port
    - elastic_host
    - cms_url
    - index
    additionalProperties: false

  web:
    additionalProperties: false
    properties:
      port:
        type: integer
        minimum: 1024
        maximum: 65535
      baseurl:
        type: string
        pattern: '[^/]$'
      allow_cors:
        type: boolean
        default: false
    required:
    - port
    - baseurl
    type: object

  cors:
    type: object
    additionalProperties: false
    properties:
      allow_all:
        type: boolean


  logging.dictconfig:
    additionalProperties: false
    properties:
      disable_existing_loggers:
        type: boolean
      filters:
        patternProperties:
          ^[a-zA-Z0-9._-]+$:
            additionalProperties: false
            properties:
              name:
                type: string
            type: object
        type: object
      formatters:
        patternProperties:
          '^[a-zA-Z0-9._-]+$':
            additionalProperties: false
            properties:
              datefmt:
                type: string
              format:
                type: string
            type: object
        type: object
      handlers:
        patternProperties:
          '^[a-zA-Z0-9._-]+$':
            properties:
              class:
                type: string
              filters:
                items:
                  type: string
                type: array
                uniqueItems: true
              formatter:
                type: string
              level:
                type: string
            required:
              - class
            type: object
        type: object
      incremental:
        type: boolean
      loggers:
        patternProperties:
          ^[a-zA-Z0-9._-]+$:
            properties:
              filters:
                items:
                  type: string
                type: array
                uniqueItems: true
              handlers:
                items:
                  type: string
                type: array
                uniqueItems: true
              level:
                type: string
              propagate:
                type: boolean
            type: object
        type: object
      root:
        properties:
          filters:
            items:
              type: string
            type: array
            uniqueItems: true
          handlers:
            items:
              type: string
            type: array
            uniqueItems: true
          level:
            enum:
              - CRITICAL
              - ERROR
              - WARNING
              - INFO
              - DEBUG
            type: string
        type: object
      version:
        enum:
          - 1
        type: integer
    required:
      - version
    type: object
